### PR TITLE
Fix action/checkout

### PR DESCRIPTION
**Pull request by ur4t**

### CODE REVIEW

**Comment by zhyncs** [comment]
`zhyncs/fix` works for me https://github.com/flashinfer-ai/flashinfer-nightly/actions/runs/12368955686
May you help update on top of that? Thanks!

**Comment by ur4t** [comment]
> `zhyncs/fix` works for me https://github.com/flashinfer-ai/flashinfer-nightly/actions/runs/12368955686 May you help update on top of that? Thanks!

`zhyncs/fix` is gone now. Could you please trigger a new run on `ur4t:update-nightly-release`?

**Comment by zhyncs** [comment]
for sure

**Comment by zhyncs** [comment]
ref https://github.com/flashinfer-ai/flashinfer-nightly/actions/runs/12369963485

**Comment by ur4t** [comment]
> ref https://github.com/flashinfer-ai/flashinfer-nightly/actions/runs/12369963485

It says `mkdir: cannot create directory ‘/opt/dlami’: Permission denied`, which means `/opt/dlami` and further `/opt/dlami/nvme/flashinfer/github` is not available, even in main branch? As nightly CI in main branch runs well, maybe we can fix the error via simply replace `FLASHINFER_CI_CACHE=/opt/dlami/nvme/flashinfer/github` with `FLASHINFER_CI_CACHE=/some/writeble/path`?

**Pull request merged**
